
dropout_rate: 0.5
cell_size: 64
attn_size: 64
embedding_size: 64
bidir: True
layers: 2
use_lstm: True
steps_per_checkpoint: 10000
steps_per_eval: 10000
max_steps: 500000
optimizer: 'adam'
max_input_len: 50
max_output_len: 80
batch_size: 32

data_dir: ../experiments/MBOSHI/inverse/files/
model_dir: ../experiments/MBOSHI/inverse/T2_TEMP/model
log_file: ../experiments/MBOSHI/inverse/T2_TEMP/log.txt

dev_prefix: [dev, train]

encoders:
  - name: fr

decoder:
    name: mb
